//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beneficiary
    {
        public int BId { get; set; }
        public string ToFirstName { get; set; }
        public string ToLastName { get; set; }
        public int ToAccountNo { get; set; }
        public string ToEmail { get; set; }
        public long ToPhone { get; set; }
        public int ToAmount { get; set; }
        public int AccountNo { get; set; }
    }
}
