//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestChequeBook
    {
        public string Username { get; set; }
        public string Status { get; set; }
        public System.DateTime DateAndTime { get; set; }
    }
}
