//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionId { get; set; }
        public System.DateTime DateAndTime { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Debt { get; set; }
        public Nullable<int> Credit { get; set; }
        public int Balance { get; set; }
        public int AccountNo { get; set; }
    }
}
